### PR TITLE
adjust wording

### PR DESCRIPTION
**Pull request by lsmith77**

### CODE REVIEW

**Comment by lsmith77** [comment]
sorry .. this was not intended to be send here.

FYI we are using this tool for ISO 27001 related reporting

**Comment by mrbobbytables** [comment]
Actually @lsmith77 if you don't mind me asking, what other group are you using this for? We haven't really had other groups chime in on using it :)

**Comment by lsmith77** [comment]
so I am using this for a corporate use case to make it easy to report discussions if they are risk related. 

I initially found this tool while looking for ways to handle CoC reporting within the Symfony slack. but so far our team of people handling CoC reports didn’t think its needed just yet.

**Comment by mrbobbytables** [comment]
Ahh. Thanks!

**Pull request closed without merging**
