### PR TITLE
slack-moderator-words: dont try to join an archived channel

### PR DESCRIPTION
**Pull request by cpanato**
/assign @nikhita @ameukam

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
Makes sense 👍 

/lgtm

/assign @jeefy 
for approval

**Comment by ameukam** [comment]
/lgtm
/approve
/hold
`/hold cancel` when you're ready to deploy.

**Comment by cpanato** [comment]
@ameukam need jeefy approval and after that we need to update the deployment with the new image :)

**Comment by ameukam** [comment]
@cpanato E_TOO_MANY_REPOS sorry!

**Pull request merged**
